---
- name: Install Tomcat9 and Apache2
  hosts: localhost
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Install Tomcat9
      apt:
        name: tomcat9
        state: present

    - name: Ensure Apache2 is running
      service:
        name: apache2
        state: started
        enabled:
